// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart' as widgets;
import 'package:hugeicons/hugeicons.dart' as huge;

typedef IconData = List<List<dynamic>>;

abstract final class Icons {
  static const IconData account_balance_wallet_rounded = huge.HugeIcons.strokeRoundedWallet01;
  static const IconData account_tree_outlined = huge.HugeIcons.strokeRoundedGitBranch;
  static const IconData account_tree_rounded = huge.HugeIcons.strokeRoundedGitBranch;
  static const IconData add_circle_outline_rounded = huge.HugeIcons.strokeRoundedAddCircle;
  static const IconData add_link_rounded = huge.HugeIcons.strokeRoundedLink04;
  static const IconData add_photo_alternate_rounded = huge.HugeIcons.strokeRoundedImageAdd01;
  static const IconData add_rounded = huge.HugeIcons.strokeRoundedAdd01;
  static const IconData ads_click_rounded = huge.HugeIcons.strokeRoundedCursorPointer01;
  static const IconData all_inbox_rounded = huge.HugeIcons.strokeRoundedInbox;
  static const IconData all_inclusive_rounded = huge.HugeIcons.strokeRoundedInfinity01;
  static const IconData alt_route_rounded = huge.HugeIcons.strokeRoundedGitBranch;
  static const IconData archive_outlined = huge.HugeIcons.strokeRoundedArchive;
  static const IconData archive_rounded = huge.HugeIcons.strokeRoundedArchive;
  static const IconData arrow_back_rounded = huge.HugeIcons.strokeRoundedArrowLeft01;
  static const IconData arrow_downward_rounded = huge.HugeIcons.strokeRoundedArrowDown01;
  static const IconData arrow_forward_rounded = huge.HugeIcons.strokeRoundedArrowRight01;
  static const IconData arrow_upward_rounded = huge.HugeIcons.strokeRoundedArrowUp01;
  static const IconData article_rounded = huge.HugeIcons.strokeRoundedFile01;
  static const IconData aspect_ratio_rounded = huge.HugeIcons.strokeRoundedMaximize01;
  static const IconData attachment_rounded = huge.HugeIcons.strokeRoundedAttachment01;
  static const IconData audio_file_rounded = huge.HugeIcons.strokeRoundedFileAudio;
  static const IconData auto_awesome_mosaic_rounded = huge.HugeIcons.strokeRoundedSparkles;
  static const IconData auto_awesome_rounded = huge.HugeIcons.strokeRoundedSparkles;
  static const IconData badge_rounded = huge.HugeIcons.strokeRoundedId;
  static const IconData block_rounded = huge.HugeIcons.strokeRoundedCancelCircle;
  static const IconData bolt_rounded = huge.HugeIcons.strokeRoundedZap;
  static const IconData brightness_6_rounded = huge.HugeIcons.strokeRoundedCircle;
  static const IconData brightness_auto_rounded = huge.HugeIcons.strokeRoundedSun03;
  static const IconData broken_image_rounded = huge.HugeIcons.strokeRoundedImageNotFound01;
  static const IconData center_focus_strong_rounded = huge.HugeIcons.strokeRoundedTarget01;
  static const IconData chat_bubble_outline_rounded = huge.HugeIcons.strokeRoundedBubbleChat;
  static const IconData check_circle_outline_rounded = huge.HugeIcons.strokeRoundedCheckmarkCircle01;
  static const IconData check_circle_rounded = huge.HugeIcons.strokeRoundedCheckmarkCircle01;
  static const IconData check_rounded = huge.HugeIcons.strokeRoundedTick02;
  static const IconData checklist_rounded = huge.HugeIcons.strokeRoundedCheckList;
  static const IconData chevron_left_rounded = huge.HugeIcons.strokeRoundedArrowLeft01;
  static const IconData chevron_right_rounded = huge.HugeIcons.strokeRoundedArrowRight01;
  static const IconData circle_outlined = huge.HugeIcons.strokeRoundedCircle;
  static const IconData clear_all_rounded = huge.HugeIcons.strokeRoundedLeftToRightListBullet;
  static const IconData close_fullscreen_rounded = huge.HugeIcons.strokeRoundedMinimize01;
  static const IconData close_rounded = huge.HugeIcons.strokeRoundedCancel01;
  static const IconData cloud_off_rounded = huge.HugeIcons.strokeRoundedCloudOff;
  static const IconData cloud_sync_rounded = huge.HugeIcons.strokeRoundedCloudUpload;
  static const IconData code_rounded = huge.HugeIcons.strokeRoundedCode;
  static const IconData compress_rounded = huge.HugeIcons.strokeRoundedMinimize01;
  static const IconData construction_outlined = huge.HugeIcons.strokeRoundedWrench01;
  static const IconData construction_rounded = huge.HugeIcons.strokeRoundedWrench01;
  static const IconData content_copy_rounded = huge.HugeIcons.strokeRoundedCopy01;
  static const IconData content_cut_rounded = huge.HugeIcons.strokeRoundedScissor01;
  static const IconData cookie_outlined = huge.HugeIcons.strokeRoundedCookie;
  static const IconData copy_all_rounded = huge.HugeIcons.strokeRoundedCopy02;
  static const IconData copy_rounded = huge.HugeIcons.strokeRoundedCopy01;
  static const IconData dark_mode_rounded = huge.HugeIcons.strokeRoundedMoon02;
  static const IconData data_object_rounded = huge.HugeIcons.strokeRoundedCode;
  static const IconData data_usage_rounded = huge.HugeIcons.strokeRoundedPieChart;
  static const IconData delete_outline = huge.HugeIcons.strokeRoundedDelete02;
  static const IconData delete_outline_rounded = huge.HugeIcons.strokeRoundedDelete02;
  static const IconData delete_sweep_outlined = huge.HugeIcons.strokeRoundedClean;
  static const IconData delete_sweep_rounded = huge.HugeIcons.strokeRoundedClean;
  static const IconData description_outlined = huge.HugeIcons.strokeRoundedFile01;
  static const IconData description_rounded = huge.HugeIcons.strokeRoundedFile01;
  static const IconData desktop_mac_rounded = huge.HugeIcons.strokeRoundedComputer;
  static const IconData devices_other_rounded = huge.HugeIcons.strokeRoundedComputerPhoneSync;
  static const IconData devices_rounded = huge.HugeIcons.strokeRoundedComputerPhoneSync;
  static const IconData difference_rounded = huge.HugeIcons.strokeRoundedGitCompare;
  static const IconData dns_rounded = huge.HugeIcons.strokeRoundedServerStack01;
  static const IconData downloading_rounded = huge.HugeIcons.strokeRoundedDownload01;
  static const IconData drive_file_rename_outline = huge.HugeIcons.strokeRoundedFileEdit;
  static const IconData edit_note_rounded = huge.HugeIcons.strokeRoundedNoteEdit;
  static const IconData edit_outlined = huge.HugeIcons.strokeRoundedEdit02;
  static const IconData edit_rounded = huge.HugeIcons.strokeRoundedEdit02;
  static const IconData error_outline_rounded = huge.HugeIcons.strokeRoundedAlertCircle;
  static const IconData expand_less_rounded = huge.HugeIcons.strokeRoundedArrowUp01;
  static const IconData expand_more_rounded = huge.HugeIcons.strokeRoundedArrowDown01;
  static const IconData extension_rounded = huge.HugeIcons.strokeRoundedPuzzle;
  static const IconData fact_check_rounded = huge.HugeIcons.strokeRoundedTask01;
  static const IconData filter_alt_off_rounded = huge.HugeIcons.strokeRoundedFilterRemove;
  static const IconData fit_screen_rounded = huge.HugeIcons.strokeRoundedMaximize01;
  static const IconData flag_rounded = huge.HugeIcons.strokeRoundedFlag01;
  static const IconData folder_copy_rounded = huge.HugeIcons.strokeRoundedFolderTransfer;
  static const IconData folder_open_rounded = huge.HugeIcons.strokeRoundedFolderOpen;
  static const IconData folder_outlined = huge.HugeIcons.strokeRoundedFolder01;
  static const IconData folder_rounded = huge.HugeIcons.strokeRoundedFolder01;
  static const IconData folder_special_rounded = huge.HugeIcons.strokeRoundedFolderSecurity;
  static const IconData font_download_rounded = huge.HugeIcons.strokeRoundedTextFont;
  static const IconData format_size_rounded = huge.HugeIcons.strokeRoundedTextFont;
  static const IconData forum_rounded = huge.HugeIcons.strokeRoundedBubbleChat;
  static const IconData fullscreen_rounded = huge.HugeIcons.strokeRoundedMaximize01;
  static const IconData gpp_maybe_rounded = huge.HugeIcons.strokeRoundedSecurityWarning;
  static const IconData graphic_eq_rounded = huge.HugeIcons.strokeRoundedChartHistogram;
  static const IconData grid_view_rounded = huge.HugeIcons.strokeRoundedGridView;
  static const IconData help_outline_rounded = huge.HugeIcons.strokeRoundedHelpCircle;
  static const IconData history_rounded = huge.HugeIcons.strokeRoundedTimeQuarterPass;
  static const IconData history_toggle_off_rounded = huge.HugeIcons.strokeRoundedTimeManagement;
  static const IconData home_rounded = huge.HugeIcons.strokeRoundedHome01;
  static const IconData hourglass_top_rounded = huge.HugeIcons.strokeRoundedHourglass;
  static const IconData hub_rounded = huge.HugeIcons.strokeRoundedShare01;
  static const IconData image_rounded = huge.HugeIcons.strokeRoundedImage01;
  static const IconData info_outline_rounded = huge.HugeIcons.strokeRoundedInformationCircle;
  static const IconData input_rounded = huge.HugeIcons.strokeRoundedLogin01;
  static const IconData insert_drive_file_rounded = huge.HugeIcons.strokeRoundedFile01;
  static const IconData inventory_2_rounded = huge.HugeIcons.strokeRoundedPackage;
  static const IconData key_off_rounded = huge.HugeIcons.strokeRoundedKey02;
  static const IconData key_rounded = huge.HugeIcons.strokeRoundedKey01;
  static const IconData keyboard_alt_rounded = huge.HugeIcons.strokeRoundedKeyboard;
  static const IconData keyboard_arrow_down_rounded = huge.HugeIcons.strokeRoundedArrowDown01;
  static const IconData keyboard_arrow_right_rounded = huge.HugeIcons.strokeRoundedArrowRight01;
  static const IconData keyboard_arrow_up_rounded = huge.HugeIcons.strokeRoundedArrowUp01;
  static const IconData keyboard_command_key_rounded = huge.HugeIcons.strokeRoundedCommand;
  static const IconData keyboard_hide_rounded = huge.HugeIcons.strokeRoundedKeyboard;
  static const IconData keyboard_rounded = huge.HugeIcons.strokeRoundedKeyboard;
  static const IconData label_rounded = huge.HugeIcons.strokeRoundedTag01;
  static const IconData layers_rounded = huge.HugeIcons.strokeRoundedLayers01;
  static const IconData light_mode_rounded = huge.HugeIcons.strokeRoundedSun03;
  static const IconData link_rounded = huge.HugeIcons.strokeRoundedLink04;
  static const IconData list_alt_rounded = huge.HugeIcons.strokeRoundedLeftToRightListBullet;
  static const IconData lock_clock_rounded = huge.HugeIcons.strokeRoundedLockKey;
  static const IconData lock_open_rounded = huge.HugeIcons.strokeRoundedLocker;
  static const IconData lock_outline_rounded = huge.HugeIcons.strokeRoundedLock;
  static const IconData lock_reset_rounded = huge.HugeIcons.strokeRoundedLockPassword;
  static const IconData lock_rounded = huge.HugeIcons.strokeRoundedLock;
  static const IconData manage_search_rounded = huge.HugeIcons.strokeRoundedSearchList01;
  static const IconData mark_chat_unread_rounded = huge.HugeIcons.strokeRoundedMessageNotification01;
  static const IconData medical_services_rounded = huge.HugeIcons.strokeRoundedFirstAidKit;
  static const IconData memory_rounded = huge.HugeIcons.strokeRoundedCpu;
  static const IconData menu_rounded = huge.HugeIcons.strokeRoundedMenu01;
  static const IconData more_horiz_rounded = huge.HugeIcons.strokeRoundedMoreHorizontal;
  static const IconData more_vert_rounded = huge.HugeIcons.strokeRoundedMoreVertical;
  static const IconData notifications_active_rounded = huge.HugeIcons.strokeRoundedNotification03;
  static const IconData notifications_off_rounded = huge.HugeIcons.strokeRoundedNotificationOff01;
  static const IconData notifications_paused_rounded = huge.HugeIcons.strokeRoundedNotificationSnooze01;
  static const IconData notifications_rounded = huge.HugeIcons.strokeRoundedNotification01;
  static const IconData open_in_browser_rounded = huge.HugeIcons.strokeRoundedBrowser;
  static const IconData open_in_new_rounded = huge.HugeIcons.strokeRoundedArrowUpRight01;
  static const IconData outbox_rounded = huge.HugeIcons.strokeRoundedInboxUpload;
  static const IconData palette_outlined = huge.HugeIcons.strokeRoundedPaintBoard;
  static const IconData palette_rounded = huge.HugeIcons.strokeRoundedPaintBoard;
  static const IconData pause_circle_filled_rounded = huge.HugeIcons.strokeRoundedPauseCircle;
  static const IconData pause_circle_outline_rounded = huge.HugeIcons.strokeRoundedPauseCircle;
  static const IconData pause_rounded = huge.HugeIcons.strokeRoundedPause;
  static const IconData perm_media_rounded = huge.HugeIcons.strokeRoundedAlbum02;
  static const IconData person_outline_rounded = huge.HugeIcons.strokeRoundedUser;
  static const IconData phone_android_rounded = huge.HugeIcons.strokeRoundedSmartPhone01;
  static const IconData picture_as_pdf_rounded = huge.HugeIcons.strokeRoundedPdf01;
  static const IconData play_arrow_rounded = huge.HugeIcons.strokeRoundedPlay;
  static const IconData play_circle_fill_rounded = huge.HugeIcons.strokeRoundedPlayCircle;
  static const IconData play_circle_outline_rounded = huge.HugeIcons.strokeRoundedPlayCircle;
  static const IconData playlist_play_rounded = huge.HugeIcons.strokeRoundedPlaylist01;
  static const IconData psychology_alt_rounded = huge.HugeIcons.strokeRoundedAiBrain01;
  static const IconData psychology_outlined = huge.HugeIcons.strokeRoundedAiBrain01;
  static const IconData public_off_rounded = huge.HugeIcons.strokeRoundedGlobe02;
  static const IconData public_rounded = huge.HugeIcons.strokeRoundedGlobe02;
  static const IconData push_pin_outlined = huge.HugeIcons.strokeRoundedPin;
  static const IconData push_pin_rounded = huge.HugeIcons.strokeRoundedPin;
  static const IconData qr_code_scanner_rounded = huge.HugeIcons.strokeRoundedQrCode;
  static const IconData question_answer_outlined = huge.HugeIcons.strokeRoundedMessageQuestion;
  static const IconData queue_rounded = huge.HugeIcons.strokeRoundedQueue01;
  static const IconData radio_button_checked_rounded = huge.HugeIcons.strokeRoundedRecord;
  static const IconData radio_button_off_rounded = huge.HugeIcons.strokeRoundedCircle;
  static const IconData radio_button_unchecked_rounded = huge.HugeIcons.strokeRoundedCircle;
  static const IconData rate_review_rounded = huge.HugeIcons.strokeRoundedComment01;
  static const IconData refresh_rounded = huge.HugeIcons.strokeRoundedRefresh;
  static const IconData remove_rounded = huge.HugeIcons.strokeRoundedMinusSign;
  static const IconData replay_circle_filled_rounded = huge.HugeIcons.strokeRoundedReload;
  static const IconData replay_rounded = huge.HugeIcons.strokeRoundedReload;
  static const IconData report_problem_outlined = huge.HugeIcons.strokeRoundedAlert02;
  static const IconData restart_alt_rounded = huge.HugeIcons.strokeRoundedRefresh;
  static const IconData rocket_launch_rounded = huge.HugeIcons.strokeRoundedRocket01;
  static const IconData route_rounded = huge.HugeIcons.strokeRoundedRoute01;
  static const IconData rule_folder_rounded = huge.HugeIcons.strokeRoundedFolderLibrary;
  static const IconData save_outlined = huge.HugeIcons.strokeRoundedFloppyDisk;
  static const IconData save_rounded = huge.HugeIcons.strokeRoundedFloppyDisk;
  static const IconData schedule_rounded = huge.HugeIcons.strokeRoundedClock01;
  static const IconData science_rounded = huge.HugeIcons.strokeRoundedTestTube01;
  static const IconData screen_lock_portrait_rounded = huge.HugeIcons.strokeRoundedPhoneLock;
  static const IconData search_off_rounded = huge.HugeIcons.strokeRoundedSearchRemove;
  static const IconData search_rounded = huge.HugeIcons.strokeRoundedSearch01;
  static const IconData send_rounded = huge.HugeIcons.strokeRoundedSent;
  static const IconData sensors_rounded = huge.HugeIcons.strokeRoundedWifi01;
  static const IconData shield_rounded = huge.HugeIcons.strokeRoundedShield01;
  static const IconData shortcut_rounded = huge.HugeIcons.strokeRoundedArrowTurnBackward;
  static const IconData smart_toy_rounded = huge.HugeIcons.strokeRoundedRobot01;
  static const IconData smartphone_rounded = huge.HugeIcons.strokeRoundedSmartPhone01;
  static const IconData speed_rounded = huge.HugeIcons.strokeRoundedDashboardSpeed01;
  static const IconData star_outline_rounded = huge.HugeIcons.strokeRoundedStar;
  static const IconData star_rounded = huge.HugeIcons.strokeRoundedStar;
  static const IconData stop_circle_outlined = huge.HugeIcons.strokeRoundedStopCircle;
  static const IconData stop_circle_rounded = huge.HugeIcons.strokeRoundedStopCircle;
  static const IconData storage_rounded = huge.HugeIcons.strokeRoundedDatabase;
  static const IconData sync_problem_rounded = huge.HugeIcons.strokeRoundedRefresh;
  static const IconData sync_rounded = huge.HugeIcons.strokeRoundedRefresh;
  static const IconData system_update_alt_rounded = huge.HugeIcons.strokeRoundedDownload01;
  static const IconData system_update_rounded = huge.HugeIcons.strokeRoundedDownload01;
  static const IconData table_chart_rounded = huge.HugeIcons.strokeRoundedTable;
  static const IconData tag_rounded = huge.HugeIcons.strokeRoundedTag01;
  static const IconData terminal_rounded = huge.HugeIcons.strokeRoundedComputerTerminal01;
  static const IconData thumb_down_alt_rounded = huge.HugeIcons.strokeRoundedThumbsDown;
  static const IconData timelapse_rounded = huge.HugeIcons.strokeRoundedTimer01;
  static const IconData timer_outlined = huge.HugeIcons.strokeRoundedTimer01;
  static const IconData travel_explore_rounded = huge.HugeIcons.strokeRoundedGlobe02;
  static const IconData tune_rounded = huge.HugeIcons.strokeRoundedSettings02;
  static const IconData unarchive_rounded = huge.HugeIcons.strokeRoundedArchiveRestore;
  static const IconData unfold_less_rounded = huge.HugeIcons.strokeRoundedMinimize01;
  static const IconData unfold_more_rounded = huge.HugeIcons.strokeRoundedMaximize01;
  static const IconData update_rounded = huge.HugeIcons.strokeRoundedRefresh;
  static const IconData verified_rounded = huge.HugeIcons.strokeRoundedCheckmarkBadge01;
  static const IconData verified_user_outlined = huge.HugeIcons.strokeRoundedShieldUser;
  static const IconData verified_user_rounded = huge.HugeIcons.strokeRoundedShieldUser;
  static const IconData view_agenda_rounded = huge.HugeIcons.strokeRoundedLayoutTable01;
  static const IconData view_sidebar_rounded = huge.HugeIcons.strokeRoundedSidebarLeft;
  static const IconData visibility_off_rounded = huge.HugeIcons.strokeRoundedViewOff;
  static const IconData visibility_rounded = huge.HugeIcons.strokeRoundedView;
  static const IconData warning_amber_rounded = huge.HugeIcons.strokeRoundedAlert02;
  static const IconData widgets_rounded = huge.HugeIcons.strokeRoundedDashboardSquare01;
  static const IconData wifi_off_rounded = huge.HugeIcons.strokeRoundedWifiOff01;
  static const IconData wifi_tethering_rounded = huge.HugeIcons.strokeRoundedWifi01;
}

class Icon extends widgets.StatelessWidget {
  const Icon(this.icon, {super.key, this.size, this.color});

  final IconData? icon;
  final double? size;
  final widgets.Color? color;

  @override
  widgets.Widget build(widgets.BuildContext context) {
    final icon = this.icon;
    if (icon == null) {
      return const widgets.SizedBox.shrink();
    }
    return huge.HugeIcon(icon: icon, size: size, color: color);
  }
}
