import { execFile } from "node:child_process";
import { access, chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { promisify } from "node:util";

import type { NodeConfig } from "./types.js";

const execFileAsync = promisify(execFile);

export const DEFAULT_LAUNCHD_LABEL = "dev.sidemesh.daemon";

export interface LaunchdPaths {
  label: string;
  packageDir: string;
  nodeBin: string;
  plistPath: string;
  envPath: string;
  launcherPath: string;
  stdoutPath: string;
  stderrPath: string;
}

export interface InstallLaunchdOptions {
  label?: string | null;
  packageDir: string;
  nodeBin: string;
  plistPath?: string | null;
  envPath?: string | null;
  launcherPath?: string | null;
  start: boolean;
}

export interface UninstallLaunchdOptions {
  label?: string | null;
  plistPath?: string | null;
  envPath?: string | null;
  launcherPath?: string | null;
  removeFiles: boolean;
}

export function resolveLaunchdPaths(
  config: Pick<NodeConfig, "stateDir">,
  options: {
    label?: string | null;
    packageDir: string;
    nodeBin: string;
    plistPath?: string | null;
    envPath?: string | null;
    launcherPath?: string | null;
  },
): LaunchdPaths {
  const label = normalizeLaunchdLabel(options.label);
  const launchdStateDir = join(config.stateDir, "launchd");
  return {
    label,
    packageDir: options.packageDir,
    nodeBin: options.nodeBin,
    plistPath:
      options.plistPath?.trim() ||
      join(homedir(), "Library", "LaunchAgents", `${label}.plist`),
    envPath: options.envPath?.trim() || join(launchdStateDir, `${label}.env`),
    launcherPath:
      options.launcherPath?.trim() || join(launchdStateDir, `${label}.sh`),
    stdoutPath: join(launchdStateDir, `${label}.out.log`),
    stderrPath: join(launchdStateDir, `${label}.err.log`),
  };
}

export function renderLaunchdPlist(paths: LaunchdPaths): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(paths.label)}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(paths.launcherPath)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${escapeXml(paths.packageDir)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${escapeXml(paths.stdoutPath)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(paths.stderrPath)}</string>
</dict>
</plist>
`;
}

export function renderLaunchdLauncher(
  paths: LaunchdPaths,
  config: Pick<NodeConfig, "configPath">,
): string {
  return `#!/usr/bin/env bash
set -euo pipefail
set -a
. ${shellQuote(paths.envPath)}
set +a
export PATH=${shellQuote(dirname(paths.nodeBin))}:$PATH
cd ${shellQuote(paths.packageDir)}
exec ${shellQuote(paths.nodeBin)} ${shellQuote(join(paths.packageDir, "dist", "cli.js"))} daemon --config ${shellQuote(config.configPath)}
`;
}

export function renderLaunchdEnv(config: NodeConfig): string {
  const lines = [
    "# Generated by `sidemesh service install`.",
    "# Contains the bearer token used by Sidemesh clients; keep this file private.",
    envLine("SIDEMESH_CONFIG", config.configPath),
    envLine("SIDEMESH_LABEL", config.label),
    envLine("SIDEMESH_PORT", String(config.port)),
    envLine("SIDEMESH_TOKEN", config.token),
    envLine("SIDEMESH_STATE_DIR", config.stateDir),
    envLine("SIDEMESH_TERMINAL", config.terminal.enabled ? "1" : "0"),
    envLine(
      "SIDEMESH_PORT_FORWARDING",
      config.portForwarding.enabled ? "1" : "0",
    ),
    envLine(
      "SIDEMESH_PORT_FORWARDING_ALLOW_NON_LOOPBACK",
      config.portForwarding.allowNonLoopbackTargets ? "1" : "0",
    ),
    envLine(
      "SIDEMESH_TERMINAL_REQUIRE_PTY",
      config.terminal.requirePty ? "1" : "0",
    ),
  ];
  if (config.terminal.shell) {
    lines.push(envLine("SIDEMESH_TERMINAL_SHELL", config.terminal.shell));
  }
  return `${lines.join("\n")}\n`;
}

export async function installLaunchdService(
  config: NodeConfig,
  options: InstallLaunchdOptions,
): Promise<LaunchdPaths> {
  assertLaunchdHost();
  const paths = resolveLaunchdPaths(config, options);
  await assertCompiledCli(paths.packageDir);

  await mkdir(dirname(paths.plistPath), { recursive: true, mode: 0o755 });
  await mkdir(dirname(paths.envPath), { recursive: true, mode: 0o700 });
  await mkdir(dirname(paths.launcherPath), { recursive: true, mode: 0o700 });
  await writeFile(paths.envPath, renderLaunchdEnv(config), { mode: 0o600 });
  await writeFile(paths.launcherPath, renderLaunchdLauncher(paths, config), {
    mode: 0o755,
  });
  await chmod(paths.launcherPath, 0o755);
  await writeFile(paths.plistPath, renderLaunchdPlist(paths), { mode: 0o644 });

  await launchctl(["bootout", launchdTarget(), paths.plistPath]).catch(
    () => undefined,
  );
  if (options.start) {
    await launchctl(["bootstrap", launchdTarget(), paths.plistPath]);
    await launchctl(["enable", `${launchdTarget()}/${paths.label}`]).catch(
      () => undefined,
    );
    await launchctl(["kickstart", "-k", `${launchdTarget()}/${paths.label}`]);
  }
  return paths;
}

export async function restartLaunchdService(
  label?: string | null,
): Promise<void> {
  assertLaunchdHost();
  await launchctl(["kickstart", "-k", `${launchdTarget()}/${normalizeLaunchdLabel(label)}`]);
}

export async function uninstallLaunchdService(
  config: Pick<NodeConfig, "stateDir">,
  options: UninstallLaunchdOptions,
): Promise<LaunchdPaths> {
  assertLaunchdHost();
  const paths = resolveLaunchdPaths(config, {
    label: options.label,
    packageDir: "",
    nodeBin: "",
    plistPath: options.plistPath,
    envPath: options.envPath,
    launcherPath: options.launcherPath,
  });

  await launchctl(["bootout", launchdTarget(), paths.plistPath]).catch(
    () => undefined,
  );
  await launchctl(["disable", `${launchdTarget()}/${paths.label}`]).catch(
    () => undefined,
  );
  if (options.removeFiles) {
    await rm(paths.plistPath, { force: true });
    await rm(paths.envPath, { force: true });
    await rm(paths.launcherPath, { force: true });
  }
  return paths;
}

export async function launchdServiceStatus(
  label?: string | null,
): Promise<string> {
  assertLaunchdHost();
  try {
    const { stdout, stderr } = await execFileAsync("launchctl", [
      "print",
      `${launchdTarget()}/${normalizeLaunchdLabel(label)}`,
    ]);
    return `${stdout}${stderr}`;
  } catch (error) {
    const typed = error as NodeJS.ErrnoException & {
      stdout?: string;
      stderr?: string;
    };
    const output = `${typed.stdout ?? ""}${typed.stderr ?? ""}`;
    if (output) return output;
    return `${normalizeLaunchdLabel(label)} is not loaded.\n`;
  }
}

export async function isLaunchdServiceLoaded(
  label?: string | null,
): Promise<boolean> {
  assertLaunchdHost();
  try {
    await launchctl(["print", `${launchdTarget()}/${normalizeLaunchdLabel(label)}`]);
    return true;
  } catch {
    return false;
  }
}

export function assertLaunchdHost(): void {
  if (process.platform !== "darwin") {
    throw new Error("Sidemesh launchd helpers currently support macOS only.");
  }
  if (process.getuid?.() === 0) {
    throw new Error(
      "Do not run macOS LaunchAgent commands with sudo; install Sidemesh as your normal user.",
    );
  }
}

async function assertCompiledCli(packageDir: string): Promise<void> {
  try {
    await access(join(packageDir, "dist", "cli.js"));
  } catch {
    throw new Error(
      `Compiled CLI not found at ${join(packageDir, "dist", "cli.js")}. Run \`npm install\` and \`npm run build\` first.`,
    );
  }
}

async function launchctl(args: string[]): Promise<void> {
  await execFileAsync("launchctl", args);
}

function launchdTarget(): string {
  return `gui/${process.getuid?.() ?? 501}`;
}

function normalizeLaunchdLabel(value: string | null | undefined): string {
  const label = value?.trim() || DEFAULT_LAUNCHD_LABEL;
  if (!/^[A-Za-z0-9_.-]+$/.test(label)) {
    throw new Error(`Invalid launchd label: ${label}`);
  }
  return label;
}

function envLine(key: string, value: string): string {
  return `${key}=${environmentValue(value)}`;
}

function environmentValue(value: string): string {
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(value)) {
    return value;
  }
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")}"`;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
