import { execFile } from "node:child_process";
import { access, chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";

import type { NodeConfig } from "./types.js";

const execFileAsync = promisify(execFile);

export const DEFAULT_SERVICE_NAME = "sidemesh";
export const DEFAULT_SERVICE_DIR = "/etc/sidemesh";

export interface ServicePaths {
  serviceName: string;
  packageDir: string;
  nodeBin: string;
  unitPath: string;
  envPath: string;
  launcherPath: string;
}

export interface InstallServiceOptions {
  serviceName?: string | null;
  packageDir: string;
  nodeBin: string;
  unitPath?: string | null;
  envPath?: string | null;
  launcherPath?: string | null;
  memoryHigh?: string | null;
  memoryMax?: string | null;
  start: boolean;
}

export interface UninstallServiceOptions {
  serviceName?: string | null;
  unitPath?: string | null;
  envPath?: string | null;
  launcherPath?: string | null;
  removeFiles: boolean;
}

export function resolveServicePaths(options: {
  serviceName?: string | null;
  packageDir: string;
  nodeBin: string;
  unitPath?: string | null;
  envPath?: string | null;
  launcherPath?: string | null;
}): ServicePaths {
  const serviceName = normalizeServiceName(options.serviceName);
  return {
    serviceName,
    packageDir: options.packageDir,
    nodeBin: options.nodeBin,
    unitPath:
      options.unitPath?.trim() ||
      `/etc/systemd/system/${serviceName}.service`,
    envPath:
      options.envPath?.trim() ||
      join(DEFAULT_SERVICE_DIR, `${serviceName}.env`),
    launcherPath:
      options.launcherPath?.trim() ||
      join(DEFAULT_SERVICE_DIR, `${serviceName}.sh`),
  };
}

export function renderSystemdUnit(
  paths: ServicePaths,
  limits: { memoryHigh?: string | null; memoryMax?: string | null } = {},
): string {
  const memoryHigh = normalizeSystemdSize(limits.memoryHigh);
  const memoryMax = normalizeSystemdSize(limits.memoryMax);
  const resourceLines = [
    "MemoryAccounting=yes",
    memoryHigh ? `MemoryHigh=${memoryHigh}` : null,
    memoryMax ? `MemoryMax=${memoryMax}` : null,
  ].filter((line): line is string => line !== null);
  return `[Unit]
Description=Sidemesh daemon
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${paths.packageDir}
EnvironmentFile=${paths.envPath}
ExecStart=${paths.launcherPath}
Restart=always
RestartSec=3
KillMode=mixed
KillSignal=SIGTERM
SendSIGKILL=yes
TimeoutStopSec=15s
${resourceLines.join("\n")}

[Install]
WantedBy=multi-user.target
`;
}

export function renderServiceLauncher(
  paths: ServicePaths,
  config: Pick<NodeConfig, "configPath">,
): string {
  return `#!/usr/bin/env bash
set -euo pipefail
export PATH=${shellQuote(dirname(paths.nodeBin))}:$PATH
cd ${shellQuote(paths.packageDir)}
exec ${shellQuote(paths.nodeBin)} ${shellQuote(join(paths.packageDir, "dist", "cli.js"))} daemon --config ${shellQuote(config.configPath)}
`;
}

export function renderServiceEnv(config: NodeConfig): string {
  const lines = [
    "# Generated by `sidemesh service install`.",
    "# Contains the bearer token used by Sidemesh clients; keep this file private.",
    envLine("SIDEMESH_CONFIG", config.configPath),
    envLine("SIDEMESH_LABEL", config.label),
    envLine("SIDEMESH_PORT", String(config.port)),
    envLine("SIDEMESH_TOKEN", config.token),
    envLine("SIDEMESH_STATE_DIR", config.stateDir),
    envLine("SIDEMESH_TERMINAL", config.terminal.enabled ? "1" : "0"),
    envLine(
      "SIDEMESH_PORT_FORWARDING",
      config.portForwarding.enabled ? "1" : "0",
    ),
    envLine(
      "SIDEMESH_PORT_FORWARDING_ALLOW_NON_LOOPBACK",
      config.portForwarding.allowNonLoopbackTargets ? "1" : "0",
    ),
    envLine(
      "SIDEMESH_TERMINAL_REQUIRE_PTY",
      config.terminal.requirePty ? "1" : "0",
    ),
  ];
  if (config.terminal.shell) {
    lines.push(envLine("SIDEMESH_TERMINAL_SHELL", config.terminal.shell));
  }
  return `${lines.join("\n")}\n`;
}

export async function installSystemdService(
  config: NodeConfig,
  options: InstallServiceOptions,
): Promise<ServicePaths> {
  assertSystemdHost({ requireRoot: true });
  const paths = resolveServicePaths(options);
  await assertCompiledCli(paths.packageDir);

  await mkdir(dirname(paths.envPath), { recursive: true, mode: 0o700 });
  await mkdir(dirname(paths.launcherPath), { recursive: true, mode: 0o755 });
  await mkdir(dirname(paths.unitPath), { recursive: true, mode: 0o755 });
  await writeFile(paths.envPath, renderServiceEnv(config), { mode: 0o600 });
  await writeFile(paths.launcherPath, renderServiceLauncher(paths, config), {
    mode: 0o755,
  });
  await chmod(paths.launcherPath, 0o755);
  await writeFile(
    paths.unitPath,
    renderSystemdUnit(paths, {
      memoryHigh: options.memoryHigh,
      memoryMax: options.memoryMax,
    }),
    { mode: 0o644 },
  );

  await systemctl(["daemon-reload"]);
  await systemctl(["enable", `${paths.serviceName}.service`]);
  if (options.start) {
    await systemctl(["restart", `${paths.serviceName}.service`]);
  }
  return paths;
}

export async function restartSystemdService(
  serviceName?: string | null,
): Promise<void> {
  assertSystemdHost({ requireRoot: true });
  await systemctl(["restart", `${normalizeServiceName(serviceName)}.service`]);
}

export async function uninstallSystemdService(
  options: UninstallServiceOptions,
): Promise<ServicePaths> {
  assertSystemdHost({ requireRoot: true });
  const paths = resolveServicePaths({
    serviceName: options.serviceName,
    packageDir: "",
    nodeBin: "",
    unitPath: options.unitPath,
    envPath: options.envPath,
    launcherPath: options.launcherPath,
  });

  await systemctl(["disable", "--now", `${paths.serviceName}.service`]).catch(
    () => undefined,
  );
  if (options.removeFiles) {
    await rm(paths.unitPath, { force: true });
    await rm(paths.envPath, { force: true });
    await rm(paths.launcherPath, { force: true });
  }
  await systemctl(["daemon-reload"]);
  return paths;
}

export async function systemdServiceStatus(
  serviceName?: string | null,
): Promise<string> {
  assertSystemdHost({ requireRoot: false });
  try {
    const { stdout, stderr } = await execFileAsync("systemctl", [
      "status",
      `${normalizeServiceName(serviceName)}.service`,
      "--no-pager",
      "-l",
    ]);
    return `${stdout}${stderr}`;
  } catch (error) {
    const typed = error as NodeJS.ErrnoException & {
      stdout?: string;
      stderr?: string;
    };
    const output = `${typed.stdout ?? ""}${typed.stderr ?? ""}`;
    if (output) return output;
    throw error;
  }
}

export async function isSystemdServiceActive(
  serviceName?: string | null,
): Promise<boolean> {
  assertSystemdHost({ requireRoot: false });
  try {
    await systemctl(["is-active", "--quiet", `${normalizeServiceName(serviceName)}.service`]);
    return true;
  } catch {
    return false;
  }
}

export function assertSystemdHost(options: { requireRoot: boolean }): void {
  if (process.platform !== "linux") {
    throw new Error("Sidemesh service helpers currently support Linux/systemd only.");
  }
  if (options.requireRoot && process.getuid?.() !== 0) {
    throw new Error("Run this command as root, for example with `sudo sidemesh service install`.");
  }
}

async function assertCompiledCli(packageDir: string): Promise<void> {
  try {
    await access(join(packageDir, "dist", "cli.js"));
  } catch {
    throw new Error(
      `Compiled CLI not found at ${join(packageDir, "dist", "cli.js")}. Run \`npm install\` and \`npm run build\` first.`,
    );
  }
}

async function systemctl(args: string[]): Promise<void> {
  await execFileAsync("systemctl", args);
}

function normalizeServiceName(value: string | null | undefined): string {
  const serviceName = value?.trim() || DEFAULT_SERVICE_NAME;
  if (!/^[A-Za-z0-9_.@-]+$/.test(serviceName)) {
    throw new Error(`Invalid systemd service name: ${serviceName}`);
  }
  return serviceName.endsWith(".service")
    ? serviceName.slice(0, -".service".length)
    : serviceName;
}

function normalizeSystemdSize(value: string | null | undefined): string | null {
  const normalized = value?.trim();
  if (!normalized) return null;
  if (
    normalized === "infinity" ||
    /^[0-9]+(?:[KMGTP]?)$/.test(normalized)
  ) {
    return normalized;
  }
  throw new Error(`Invalid systemd memory size: ${value}`);
}

function envLine(key: string, value: string): string {
  return `${key}=${environmentValue(value)}`;
}

function environmentValue(value: string): string {
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(value)) {
    return value;
  }
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")}"`;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
