// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'ghostty_vte-v0.1.3';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '4cd697e3bc04943ccda236a12a76c4491d4445d3225ab3e65505cdcc2cf7ccd3',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: '174c2fda799d8425b7ae08388cf1b8587f3caef46383b7648077b23d8e99a79c',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: 'e438dbdf980caf03e8b139dcf9364056b34ee1f513ae27c20a6f2e11e1081285',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '73ff1d51d99836eeb7cf879c3ac93c7e28f2c0d9312df324f9160bdd6db4e5e0',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: '8943f1e9ab44c4f6d70cccf59de02bd18a18030047758c7ca3ed54aa911c395f',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: 'ac1eae5665243c850b42bc93e178d2646f6598aa07de6b56d9c62a780908b6a7',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: 'f7ade82957a3a65f0a9a5afbf715ef102563df2fbf3f630dc7cb8fcf783a0436',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: 'e3f611ccf1758b503568a58ef3470f95c3ce36d46ca2f2fd76495cf9b1c104a4',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: 'e761f8c7c45c112ba3eec1b8ed47510d359e298a705f0b62bee71a12a42a0d33',
  ),
  'ios-arm64': AssetHash(
    tarball: 'vte-ios-arm64.tar.gz',
    hash: '891e0e8bd5d1cf11fcb6e4c04e5c86478284e3c5c255f6b2077c9e1563933a11',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'vte-ios-sim-arm64.tar.gz',
    hash: '23dc177f324ed82af0b69b7128c4876dfcac2be75e549a7ebac081f8efbb95d2',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'vte-ios-sim-x64.tar.gz',
    hash: '5ec18cf91d89b060251d34596d2e8f7a8b43d63b249707ece861be6f128f4088',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
